export interface CardMetric {
  current: number;
  lastMonth?: number;
  lastYear?: number;
  percentChangeMonth?: number;
  percentChangeYear?: number;
  currency?: string;
  unit?: string;
}

export interface CardData {
  totalRevenue: CardMetric;
  totalOrders: CardMetric;
  activeUsers: CardMetric;
  conversionRate: CardMetric;
}

export interface CardDataByDate {
  date: string;
  metrics: CardData;
}

export const cardDataByDate: CardDataByDate[] = [
  {
    date: "2025-11-01",
    metrics: {
      totalRevenue: {
        current: 120000,
        lastMonth: 110000,
        lastYear: 95000,
        percentChangeMonth: 9.1,
        percentChangeYear: 26.3,
        currency: "USD",
      },
      totalOrders: {
        current: 1100,
        lastMonth: 1050,
        lastYear: 900,
        percentChangeMonth: 4.8,
        percentChangeYear: 22.2,
      },
      activeUsers: {
        current: 3500,
        lastMonth: 3400,
        lastYear: 3000,
        percentChangeMonth: 2.9,
        percentChangeYear: 16.7,
      },
      conversionRate: {
        current: 3.1,
        lastMonth: 2.95,
        lastYear: 2.7,
        percentChangeMonth: 5.1,
        percentChangeYear: 14.8,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-02",
    metrics: {
      totalRevenue: {
        current: 145680,
        lastMonth: 132450,
        lastYear: 98320,
        percentChangeMonth: 10,
        percentChangeYear: 48.2,
        currency: "USD",
      },
      totalOrders: {
        current: 1247,
        lastMonth: 1156,
        lastYear: 892,
        percentChangeMonth: 7.9,
        percentChangeYear: 39.8,
      },
      activeUsers: {
        current: 3842,
        lastMonth: 3654,
        lastYear: 2718,
        percentChangeMonth: 5.1,
        percentChangeYear: 41.4,
      },
      conversionRate: {
        current: 3.24,
        lastMonth: 2.98,
        lastYear: 2.45,
        percentChangeMonth: 8.7,
        percentChangeYear: 32.2,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-03",
    metrics: {
      totalRevenue: {
        current: 138500,
        lastMonth: 130000,
        lastYear: 97000,
        percentChangeMonth: 6.5,
        percentChangeYear: 42.7,
        currency: "USD",
      },
      totalOrders: {
        current: 1190,
        lastMonth: 1120,
        lastYear: 880,
        percentChangeMonth: 6.3,
        percentChangeYear: 35.2,
      },
      activeUsers: {
        current: 3700,
        lastMonth: 3550,
        lastYear: 2800,
        percentChangeMonth: 4.2,
        percentChangeYear: 32.1,
      },
      conversionRate: {
        current: 3.15,
        lastMonth: 3.0,
        lastYear: 2.5,
        percentChangeMonth: 5.0,
        percentChangeYear: 26.0,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-04",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-05",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-06",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-07",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-08",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-09",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-10",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-11",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-12",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-13",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-14",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-15",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-16",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-17",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-18",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-19",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-20",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
  {
    date: "2025-11-21",
    metrics: {
      totalRevenue: {
        current: 152000,
        lastMonth: 140000,
        lastYear: 100000,
        percentChangeMonth: 8.6,
        percentChangeYear: 52,
        currency: "USD",
      },
      totalOrders: {
        current: 1300,
        lastMonth: 1200,
        lastYear: 900,
        percentChangeMonth: 8.3,
        percentChangeYear: 44.4,
      },
      activeUsers: {
        current: 3900,
        lastMonth: 3700,
        lastYear: 3000,
        percentChangeMonth: 5.4,
        percentChangeYear: 30,
      },
      conversionRate: {
        current: 3.3,
        lastMonth: 3.1,
        lastYear: 2.6,
        percentChangeMonth: 6.5,
        percentChangeYear: 26.9,
        unit: "%",
      },
    },
  },
];
